# Generated by Django 4.2.16 on 2024-11-01 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_profile_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('height', models.FloatField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='ProfileRecord',
            fields=[
                ('user_profile_record_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='체중 기록일')),
                ('user_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'db_table': 'profile_record',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
