# Generated by Django 4.2.16 on 2024-11-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='item',
        ),
        migrations.AlterModelTable(
            name='purchaserecord',
            table='purchase_record',
        ),
    ]
