# Generated by Django 4.2.16 on 2024-09-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('food_code', models.CharField(max_length=50, primary_key=True)),
                ('food_name', models.CharField(max_length=100)),
                ('representative_food_name', models.CharField(max_length=100)),
                ('food_subcategory', models.CharField(max_length=50)),
                ('serving_size', models.FloatField()),
                ('energy', models.FloatField(help_text='kcal')),
                ('moisture', models.FloatField(help_text='g')),
                ('protein', models.FloatField(help_text='g')),
                ('fat', models.FloatField(help_text='g')),
                ('ash', models.FloatField(help_text='g')),
                ('carbohydrate', models.FloatField(help_text='g')),
                ('sugars', models.FloatField(help_text='g')),
                ('dietary_fiber', models.FloatField(help_text='g')),
                ('calcium', models.FloatField(help_text='mg')),
                ('iron', models.FloatField(help_text='mg')),
                ('phosphorus', models.FloatField(help_text='mg')),
                ('potassium', models.FloatField(help_text='mg')),
                ('sodium', models.FloatField(help_text='mg')),
                ('vitamin_a', models.FloatField(help_text='μg RAE')),
                ('retinol', models.FloatField(help_text='μg')),
                ('beta_carotene', models.FloatField(help_text='μg')),
                ('thiamin', models.FloatField(help_text='mg')),
                ('riboflavin', models.FloatField(help_text='mg')),
                ('niacin', models.FloatField(help_text='mg')),
                ('vitamin_c', models.FloatField(help_text='mg')),
                ('vitamin_d', models.FloatField(help_text='μg')),
                ('cholesterol', models.FloatField(help_text='mg')),
                ('saturated_fat', models.FloatField(help_text='g')),
                ('trans_fat', models.FloatField(help_text='g')),
            ],
            options={
                'verbose_name': 'Food Nutrition',
                'verbose_name_plural': 'Food Nutrition',
            },
        ),
    ]
