# Generated by Django 4.2.16 on 2024-11-04 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='닉네임')),
                ('total_points', models.IntegerField(default=0)),
                ('height', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'profile',
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='HeightWeightRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='체중 기록일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.profile')),
            ],
            options={
                'db_table': 'height_weight_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
