# Generated by Django 4.2.16 on 2024-11-04 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heightweightrecord',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, help_text='체중 기록일'),
        ),
    ]
