# Generated by Django 4.2.16 on 2024-11-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_alter_heightweightrecord_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='consecutive_attendance_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='consecutive_goals_achieved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='cumulative_attendance_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='cumulative_goals_achieved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_attendance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_goal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
