# Generated by Django 4.2.16 on 2024-11-05 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foods',
            old_name='food_code',
            new_name='food_id',
        ),
    ]
