# Generated by Django 4.2.16 on 2024-11-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_rename_food_code_foods_food_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='serving_size',
            field=models.FloatField(help_text='g', max_length=20),
        ),
    ]
