# Generated by Django 4.2.16 on 2024-11-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_alter_foods_ash_alter_foods_beta_carotene_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foods',
            old_name='niacin',
            new_name='magnesium',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='potassium',
            new_name='potassuim',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='riboflavin',
            new_name='zinc',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='ash',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='beta_carotene',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='dietary_fiber',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='food_subcategory',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='moisture',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='representative_food_name',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='retinol',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='saturated_fat',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='thiamin',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='vitamin_a',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='vitamin_c',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='vitamin_d',
        ),
        migrations.AlterField(
            model_name='foods',
            name='carbohydrate',
            field=models.FloatField(default=0, help_text='g'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foods',
            name='energy',
            field=models.FloatField(default=0, help_text='kcal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foods',
            name='food_code',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='foods',
            name='food_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='foods',
            name='protein',
            field=models.FloatField(default=0, help_text='g'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foods',
            name='serving_size',
            field=models.CharField(help_text='g', max_length=20),
        ),
    ]
