# Generated by Django 4.2.16 on 2024-11-01 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_rename_niacin_foods_magnesium_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foods',
            old_name='potassuim',
            new_name='potassium',
        ),
    ]
