# Generated by Django 4.2.16 on 2024-11-01 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrition', '0007_rename_potassuim_foods_potassium'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMeal',
            fields=[
                ('user_meal_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('meal_type', models.CharField(choices=[('breakfast', '아침'), ('lunch', '점심'), ('dinner', '저녁')], max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.foods')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
