# Generated by Django 4.2.16 on 2024-11-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermeal',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='usermeal',
            table='meal_record',
        ),
    ]
