# Generated by Django 4.2.16 on 2024-11-05 01:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_alter_usermeal_options_alter_usermeal_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='사용자가 등록하고자 하는 날짜'),
            preserve_default=False,
        ),
    ]
