# Generated by Django 4.2.16 on 2024-11-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_usermeal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeal',
            name='serving_size',
            field=models.FloatField(default=100, help_text='음식의 양(g)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermeal',
            name='date',
            field=models.DateField(help_text='YYYY-MM-DD 형식으로 입력'),
        ),
        migrations.AlterField(
            model_name='usermeal',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', '아침'), ('lunch', '점심'), ('dinner', '저녁')], help_text='breakfast, lunch, dinner', max_length=10),
        ),
    ]
