# Generated by Django 4.2.16 on 2024-11-22 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0005_meal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
