# Generated by Django 4.2.16 on 2024-12-06 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_description_alter_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupranking',
            name='group_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='groups.group'),
        ),
    ]
