# Generated by Django 4.2.16 on 2024-12-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_groupranking_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
