# Generated by Django 4.2.16 on 2024-11-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='닉네임'),
        ),
    ]
